// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: magazin.proto

package organization_service

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Magazin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FilialId  string `protobuf:"bytes,3,opt,name=filial_id,json=filialId,proto3" json:"filial_id,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Magazin) Reset() {
	*x = Magazin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magazin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Magazin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Magazin) ProtoMessage() {}

func (x *Magazin) ProtoReflect() protoreflect.Message {
	mi := &file_magazin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Magazin.ProtoReflect.Descriptor instead.
func (*Magazin) Descriptor() ([]byte, []int) {
	return file_magazin_proto_rawDescGZIP(), []int{0}
}

func (x *Magazin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Magazin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Magazin) GetFilialId() string {
	if x != nil {
		return x.FilialId
	}
	return ""
}

func (x *Magazin) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Magazin) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateMagazin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilialId string `protobuf:"bytes,2,opt,name=filial_id,json=filialId,proto3" json:"filial_id,omitempty"`
}

func (x *CreateMagazin) Reset() {
	*x = CreateMagazin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magazin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMagazin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMagazin) ProtoMessage() {}

func (x *CreateMagazin) ProtoReflect() protoreflect.Message {
	mi := &file_magazin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMagazin.ProtoReflect.Descriptor instead.
func (*CreateMagazin) Descriptor() ([]byte, []int) {
	return file_magazin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMagazin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMagazin) GetFilialId() string {
	if x != nil {
		return x.FilialId
	}
	return ""
}

type UpdateMagazin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FilialId string `protobuf:"bytes,3,opt,name=filial_id,json=filialId,proto3" json:"filial_id,omitempty"`
}

func (x *UpdateMagazin) Reset() {
	*x = UpdateMagazin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magazin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMagazin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMagazin) ProtoMessage() {}

func (x *UpdateMagazin) ProtoReflect() protoreflect.Message {
	mi := &file_magazin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMagazin.ProtoReflect.Descriptor instead.
func (*UpdateMagazin) Descriptor() ([]byte, []int) {
	return file_magazin_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMagazin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMagazin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMagazin) GetFilialId() string {
	if x != nil {
		return x.FilialId
	}
	return ""
}

type UpdatePatchMagazin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields *_struct.Struct `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *UpdatePatchMagazin) Reset() {
	*x = UpdatePatchMagazin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magazin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePatchMagazin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatchMagazin) ProtoMessage() {}

func (x *UpdatePatchMagazin) ProtoReflect() protoreflect.Message {
	mi := &file_magazin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatchMagazin.ProtoReflect.Descriptor instead.
func (*UpdatePatchMagazin) Descriptor() ([]byte, []int) {
	return file_magazin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePatchMagazin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePatchMagazin) GetFields() *_struct.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetListMagazinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *GetListMagazinRequest) Reset() {
	*x = GetListMagazinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magazin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListMagazinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMagazinRequest) ProtoMessage() {}

func (x *GetListMagazinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magazin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMagazinRequest.ProtoReflect.Descriptor instead.
func (*GetListMagazinRequest) Descriptor() ([]byte, []int) {
	return file_magazin_proto_rawDescGZIP(), []int{4}
}

func (x *GetListMagazinRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListMagazinRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListMagazinRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetListMagazinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int64      `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Magazins []*Magazin `protobuf:"bytes,2,rep,name=magazins,proto3" json:"magazins,omitempty"`
}

func (x *GetListMagazinResponse) Reset() {
	*x = GetListMagazinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magazin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListMagazinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMagazinResponse) ProtoMessage() {}

func (x *GetListMagazinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magazin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMagazinResponse.ProtoReflect.Descriptor instead.
func (*GetListMagazinResponse) Descriptor() ([]byte, []int) {
	return file_magazin_proto_rawDescGZIP(), []int{5}
}

func (x *GetListMagazinResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetListMagazinResponse) GetMagazins() []*Magazin {
	if x != nil {
		return x.Magazins
	}
	return nil
}

type MagazinPK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MagazinPK) Reset() {
	*x = MagazinPK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magazin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagazinPK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagazinPK) ProtoMessage() {}

func (x *MagazinPK) ProtoReflect() protoreflect.Message {
	mi := &file_magazin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagazinPK.ProtoReflect.Descriptor instead.
func (*MagazinPK) Descriptor() ([]byte, []int) {
	return file_magazin_proto_rawDescGZIP(), []int{6}
}

func (x *MagazinPK) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_magazin_proto protoreflect.FileDescriptor

var file_magazin_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x07, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x6c, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x40,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x6c, 0x49, 0x64,
	0x22, 0x50, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x6c,
	0x49, 0x64, 0x22, 0x55, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x74, 0x63,
	0x68, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x5d, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x69, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x08, 0x6d, 0x61, 0x67, 0x61,
	0x7a, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x52, 0x08, 0x6d, 0x61, 0x67, 0x61, 0x7a,
	0x69, 0x6e, 0x73, 0x22, 0x1b, 0x0a, 0x09, 0x4d, 0x61, 0x67, 0x61, 0x7a, 0x69, 0x6e, 0x50, 0x4b,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_magazin_proto_rawDescOnce sync.Once
	file_magazin_proto_rawDescData = file_magazin_proto_rawDesc
)

func file_magazin_proto_rawDescGZIP() []byte {
	file_magazin_proto_rawDescOnce.Do(func() {
		file_magazin_proto_rawDescData = protoimpl.X.CompressGZIP(file_magazin_proto_rawDescData)
	})
	return file_magazin_proto_rawDescData
}

var file_magazin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_magazin_proto_goTypes = []interface{}{
	(*Magazin)(nil),                // 0: organization_service.Magazin
	(*CreateMagazin)(nil),          // 1: organization_service.CreateMagazin
	(*UpdateMagazin)(nil),          // 2: organization_service.UpdateMagazin
	(*UpdatePatchMagazin)(nil),     // 3: organization_service.UpdatePatchMagazin
	(*GetListMagazinRequest)(nil),  // 4: organization_service.GetListMagazinRequest
	(*GetListMagazinResponse)(nil), // 5: organization_service.GetListMagazinResponse
	(*MagazinPK)(nil),              // 6: organization_service.MagazinPK
	(*_struct.Struct)(nil),         // 7: google.protobuf.Struct
}
var file_magazin_proto_depIdxs = []int32{
	7, // 0: organization_service.UpdatePatchMagazin.fields:type_name -> google.protobuf.Struct
	0, // 1: organization_service.GetListMagazinResponse.magazins:type_name -> organization_service.Magazin
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_magazin_proto_init() }
func file_magazin_proto_init() {
	if File_magazin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_magazin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Magazin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magazin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMagazin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magazin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMagazin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magazin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePatchMagazin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magazin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListMagazinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magazin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListMagazinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magazin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagazinPK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_magazin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magazin_proto_goTypes,
		DependencyIndexes: file_magazin_proto_depIdxs,
		MessageInfos:      file_magazin_proto_msgTypes,
	}.Build()
	File_magazin_proto = out.File
	file_magazin_proto_rawDesc = nil
	file_magazin_proto_goTypes = nil
	file_magazin_proto_depIdxs = nil
}
